-- SHRI JI COLLECTION: backward-compatible database migration
-- Designed to preserve the existing legacy orders table (including UUID id).
-- Run once in Supabase SQL Editor after taking a database backup.
begin;

create extension if not exists pgcrypto;

-- Products table: create when absent, then add columns needed by the current API.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  category text not null,
  price numeric(12,2) not null check (price > 0),
  sale_price numeric(12,2),
  description text,
  material text,
  sizes text[] not null default '{}',
  image_urls text[] not null default '{}',
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true
);
alter table public.products add column if not exists created_at timestamptz not null default now();
alter table public.products add column if not exists name text;
alter table public.products add column if not exists category text;
alter table public.products add column if not exists price numeric(12,2);
alter table public.products add column if not exists sale_price numeric(12,2);
alter table public.products add column if not exists description text;
alter table public.products add column if not exists material text;
alter table public.products add column if not exists sizes text[] not null default '{}';
alter table public.products add column if not exists image_urls text[] not null default '{}';
alter table public.products add column if not exists stock integer not null default 0;
alter table public.products add column if not exists active boolean not null default true;

-- Accounts and admin allow-list.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  created_at timestamptz not null default now()
);
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Create the orders table when this is a fresh Supabase project. Existing tables are preserved.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null default '',
  phone text not null default '',
  address text not null default '',
  payment_method text,
  total numeric(12,2) not null default 0,
  status text not null default 'new',
  items jsonb not null default '[]'::jsonb,
  razorpay_order_id text,
  razorpay_payment_id text,
  created_at timestamptz not null default now()
);

-- Existing legacy tables may have UUID id without a default. Add one only if needed.
alter table public.orders alter column id set default gen_random_uuid();

-- Keep existing orders.id as-is (the user's current table uses UUID); add fields
-- required by current APIs and backfill legacy rows instead of dropping/recreating.
alter table public.orders add column if not exists order_number text;
alter table public.orders add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists email text;
alter table public.orders add column if not exists city text;
alter table public.orders add column if not exists state text;
alter table public.orders add column if not exists pincode text;
alter table public.orders add column if not exists payment_status text;
alter table public.orders add column if not exists order_status text;
alter table public.orders add column if not exists subtotal numeric(12,2);
alter table public.orders add column if not exists shipping numeric(12,2) not null default 0;
alter table public.orders add column if not exists idempotency_key text;
alter table public.orders add column if not exists razorpay_order_id text;
alter table public.orders add column if not exists razorpay_payment_id text;
alter table public.orders add column if not exists payment_method text;
alter table public.orders add column if not exists items jsonb;
alter table public.orders add column if not exists total numeric(12,2);
alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists phone text;
alter table public.orders add column if not exists address text;
alter table public.orders add column if not exists created_at timestamptz not null default now();

-- Backfill only missing values; preserve existing status and customer/order data.
update public.orders
set order_number = 'SJC-LEGACY-' || replace(id::text, '-', '')
where order_number is null or btrim(order_number) = '';
update public.orders set order_status = case
  when lower(coalesce(status,'')) in ('cancelled','canceled') then 'cancelled'
  when lower(coalesce(status,'')) in ('delivered') then 'delivered'
  when lower(coalesce(status,'')) in ('shipped','dispatched') then 'shipped'
  when lower(coalesce(status,'')) in ('packed') then 'packed'
  when lower(coalesce(status,'')) in ('confirmed','processing') then 'confirmed'
  else 'new' end
where order_status is null or order_status = '';
update public.orders set payment_status = case
  when razorpay_payment_id is not null and razorpay_payment_id <> '' then 'paid'
  else 'pending' end
where payment_status is null or payment_status = '';
update public.orders set subtotal = total where subtotal is null;
-- Legacy records should satisfy not-null requirements for newly introduced API fields.
update public.orders set payment_method = case when upper(coalesce(payment_method,'')) in ('ONLINE','COD') then upper(payment_method) else 'COD' end
where payment_method is null or payment_method = '';

alter table public.orders alter column order_number set not null;
alter table public.orders alter column order_status set default 'new';
alter table public.orders alter column order_status set not null;
alter table public.orders alter column payment_status set default 'pending';
alter table public.orders alter column payment_status set not null;
alter table public.orders alter column subtotal set default 0;
alter table public.orders alter column subtotal set not null;
create unique index if not exists orders_order_number_unique on public.orders(order_number);
create unique index if not exists orders_idempotency_key_unique on public.orders(idempotency_key) where idempotency_key is not null;
create unique index if not exists orders_razorpay_order_id_unique on public.orders(razorpay_order_id) where razorpay_order_id is not null;

-- RLS: APIs use the server-only service-role key; public clients can only read active products.
alter table public.products enable row level security;
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.admin_users enable row level security;
drop policy if exists "public can view active products" on public.products;
create policy "public can view active products" on public.products for select to anon, authenticated using (active = true);
drop policy if exists "users can view own profile" on public.profiles;
create policy "users can view own profile" on public.profiles for select to authenticated using (id = auth.uid());
drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "users can view own orders" on public.orders;
create policy "users can view own orders" on public.orders for select to authenticated using (user_id = auth.uid());
-- No browser policies on admin_users: only trusted server-side service role should read it.

insert into storage.buckets (id,name,public) values ('product-images','product-images',true) on conflict (id) do nothing;
drop policy if exists "public can view product images" on storage.objects;
create policy "public can view product images" on storage.objects for select to anon, authenticated using (bucket_id = 'product-images');

-- Atomic checkout: lock products, validate database prices/sizes/stock, insert order and decrement stock.
create or replace function public.sjc_create_order(p_order jsonb, p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare ln jsonb; pr public.products%rowtype; v_items jsonb := '[]'::jsonb; v_total numeric(12,2):=0; v_qty integer; v_size text; v_price numeric(12,2); v_id bigint; v_order_number text; v_existing public.orders%rowtype; v_user uuid; v_count integer;
begin
 if p_idempotency_key is null or length(p_idempotency_key)<16 or length(p_idempotency_key)>100 then raise exception 'INVALID_IDEMPOTENCY_KEY'; end if;
 select * into v_existing from public.orders where idempotency_key=p_idempotency_key;
 if found then return jsonb_build_object('order_number',v_existing.order_number,'razorpay_order_id',v_existing.razorpay_order_id,'total',v_existing.total,'payment_status',v_existing.payment_status,'payment_method',v_existing.payment_method,'existing',true); end if;
 if jsonb_typeof(p_order->'items') <> 'array' or jsonb_array_length(p_order->'items') < 1 or jsonb_array_length(p_order->'items') > 30 then raise exception 'INVALID_ITEMS'; end if;
 select count(*) into v_count from jsonb_array_elements(p_order->'items') x where coalesce(x->>'id','') !~ '^[0-9]+$' or coalesce(x->>'qty','') !~ '^[0-9]+$';
 if v_count>0 then raise exception 'INVALID_ITEMS'; end if;
 for v_id in select distinct (x->>'id')::bigint from jsonb_array_elements(p_order->'items') x order by 1 loop
   select * into pr from public.products where id=v_id for update;
   if not found or pr.active is not true then raise exception 'PRODUCT_UNAVAILABLE'; end if;
 end loop;
 for ln in select value from jsonb_array_elements(p_order->'items') loop
   v_id := (ln->>'id')::bigint; v_qty := (ln->>'qty')::integer; v_size := coalesce(ln->>'size','');
   if v_qty is null or v_qty<1 or v_qty>20 then raise exception 'INVALID_QUANTITY'; end if;
   select * into pr from public.products where id=v_id;
   if v_size<>'' and not (v_size = any(coalesce(pr.sizes,'{}'::text[]))) then raise exception 'INVALID_SIZE'; end if;
   if pr.stock < (select sum((x->>'qty')::integer) from jsonb_array_elements(p_order->'items') x where (x->>'id')::bigint=v_id) then raise exception 'INSUFFICIENT_STOCK'; end if;
   v_price := case when pr.sale_price is not null and pr.sale_price>0 and pr.sale_price<pr.price then pr.sale_price else pr.price end;
   v_total := v_total + v_price*v_qty;
   v_items := v_items || jsonb_build_array(jsonb_build_object('id',pr.id,'name',pr.name,'qty',v_qty,'size',v_size,'price',v_price));
 end loop;
 if v_total<=0 then raise exception 'INVALID_TOTAL'; end if;
 if p_order ? 'expected_total' and round(v_total*100) <> round((p_order->>'expected_total')::numeric*100) then raise exception 'PRICE_CHANGED'; end if;
 v_order_number := p_order->>'order_number';
 if v_order_number is null or length(v_order_number)>80 then raise exception 'INVALID_ORDER_NUMBER'; end if;
 v_user := nullif(p_order->>'user_id','')::uuid;
 insert into public.orders(order_number,idempotency_key,user_id,customer_name,phone,email,address,city,state,pincode,payment_method,payment_status,order_status,status,items,subtotal,shipping,total,razorpay_order_id)
 values(v_order_number,p_idempotency_key,v_user,p_order->>'customer_name',p_order->>'phone',nullif(p_order->>'email',''),p_order->>'address',nullif(p_order->>'city',''),nullif(p_order->>'state',''),p_order->>'pincode',p_order->>'payment_method','pending','new','new',v_items,v_total,0,v_total,nullif(p_order->>'razorpay_order_id','')) returning * into v_existing;
 for v_id in select distinct (x->>'id')::bigint from jsonb_array_elements(p_order->'items') x order by 1 loop
   update public.products set stock=stock-(select sum((x->>'qty')::integer) from jsonb_array_elements(p_order->'items') x where (x->>'id')::bigint=v_id) where id=v_id;
 end loop;
 return jsonb_build_object('order_number',v_order_number,'razorpay_order_id',nullif(p_order->>'razorpay_order_id',''),'total',v_total,'payment_status','pending','payment_method',p_order->>'payment_method','existing',false);
exception when unique_violation then
 select * into v_existing from public.orders where idempotency_key=p_idempotency_key;
 if found then return jsonb_build_object('order_number',v_existing.order_number,'razorpay_order_id',v_existing.razorpay_order_id,'total',v_existing.total,'payment_status',v_existing.payment_status,'payment_method',v_existing.payment_method,'existing',true); end if;
 raise;
end; $$;
revoke all on function public.sjc_create_order(jsonb,text) from public, anon, authenticated;
grant execute on function public.sjc_create_order(jsonb,text) to service_role;

-- Atomic status updates/restock. Captured online payments must be refunded separately before cancellation.
create or replace function public.sjc_set_order_status(p_order_number text,p_new_status text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare o public.orders%rowtype; ln jsonb; v_id bigint; v_qty integer;
begin
 if p_new_status not in ('new','confirmed','packed','shipped','delivered','cancelled') then raise exception 'INVALID_STATUS'; end if;
 select * into o from public.orders where order_number=p_order_number for update;
 if not found then raise exception 'ORDER_NOT_FOUND'; end if;
 if o.order_status='cancelled' and p_new_status<>'cancelled' then raise exception 'CANCELLED_ORDER_TERMINAL'; end if;
 if p_new_status='cancelled' and upper(coalesce(o.payment_method,''))='ONLINE' and o.payment_status='paid' then raise exception 'REFUND_REQUIRED'; end if;
 if p_new_status='cancelled' and o.order_status<>'cancelled' then
   for ln in select value from jsonb_array_elements(o.items) loop
     v_id := (ln->>'id')::bigint; v_qty := (ln->>'qty')::integer;
     update public.products set stock=stock+v_qty where id=v_id;
   end loop;
 end if;
 update public.orders set order_status=p_new_status,status=p_new_status where order_number=p_order_number;
 return jsonb_build_object('order_number',p_order_number,'order_status',p_new_status);
end; $$;
revoke all on function public.sjc_set_order_status(text,text) from public, anon, authenticated;
grant execute on function public.sjc_set_order_status(text,text) to service_role;

commit;
