import {admin,getUser} from "../lib/supabase.js";
import Razorpay from "razorpay";
import crypto from "crypto";
const clean=v=>typeof v==="string"?v.trim():"";
function orderNo(){return "SJC-"+Date.now().toString(36).toUpperCase()+crypto.randomBytes(4).toString("hex").toUpperCase()}
export default async function(req,res){if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});try{
 res.setHeader("Cache-Control","no-store");const key=clean(req.headers["idempotency-key"]||req.body?.idempotencyKey);if(!/^[a-zA-Z0-9_-]{16,100}$/.test(key))return res.status(400).json({error:"Please retry checkout. A valid checkout request ID is required."});
 const {data:existing,error:existingErr}=await admin.from("orders").select("order_number,razorpay_order_id,total,payment_status,payment_method,order_status").eq("idempotency_key",key).maybeSingle();if(existingErr)throw existingErr;
 if(existing){return res.json({orderNumber:existing.order_number,existing:true,razorpay:existing.razorpay_order_id?{key:process.env.PUBLIC_RAZORPAY_KEY_ID||process.env.RAZORPAY_KEY_ID,orderId:existing.razorpay_order_id,amount:Math.round(Number(existing.total)*100)}:null,paymentStatus:existing.payment_status,paymentMethod:existing.payment_method})}
 const body=req.body||{},customer=body.customer||{},raw=body.items,paymentMethod=body.paymentMethod;
 const phone=clean(customer.phone).replace(/\D/g,"");const pincode=clean(customer.pincode);
 if(!clean(customer.name)||clean(customer.name).length>120||!/^[6-9]\d{9}$/.test(phone)||!clean(customer.address)||clean(customer.address).length>500||!/^[1-9]\d{5}$/.test(pincode)||!Array.isArray(raw)||raw.length<1||raw.length>30)return res.status(400).json({error:"Please check your name, mobile, address, pincode and cart items."});
 if(customer.email&&(!/^\S+@\S+\.\S+$/.test(clean(customer.email))||clean(customer.email).length>254))return res.status(400).json({error:"Enter a valid email address."});
 if(!["COD","ONLINE"].includes(paymentMethod))return res.status(400).json({error:"Invalid payment method"});
 const parsedIds=raw.map(x=>Number(x?.id));if(parsedIds.some(x=>!Number.isSafeInteger(x)||x<=0))return res.status(400).json({error:"Invalid product selection"});const ids=[...new Set(parsedIds)];if(ids.length===0)return res.status(400).json({error:"Invalid product selection"});
 const {data:products,error:pe}=await admin.from("products").select("id,name,price,sale_price,stock,active,sizes").in("id",ids);if(pe)throw pe;if(!products||products.length!==ids.length)return res.status(400).json({error:"One or more products are unavailable"});
 for(const line of raw){const product=products.find(x=>Number(x.id)===Number(line.id));const qty=Number(line.qty);const size=clean(line.size);if(!product||!product.active||!Number.isInteger(qty)||qty<1||qty>20)return res.status(400).json({error:"Invalid product or quantity"});if(size&&!(product.sizes||[]).includes(size))return res.status(400).json({error:`Invalid size for ${product.name}`})}
 const user=await getUser(req,res);let rpId=null;
 // Razorpay order is created before the atomic DB reservation; if reservation fails this unused gateway order cannot charge the customer.
 const provisionalTotal=raw.reduce((sum,line)=>{const product=products.find(x=>Number(x.id)===Number(line.id));const price=Number(product.sale_price)>0&&Number(product.sale_price)<Number(product.price)?Number(product.sale_price):Number(product.price);return sum+price*Number(line.qty)},0);
 if(!Number.isFinite(provisionalTotal)||provisionalTotal<=0)return res.status(400).json({error:"Invalid order total"});
 if(paymentMethod==="ONLINE"){if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return res.status(503).json({error:"Online payment is not configured yet."});const rp=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});const ro=await rp.orders.create({amount:Math.round(provisionalTotal*100),currency:"INR",receipt:orderNo()});rpId=ro.id}
 const orderNumber=orderNo();const payload={order_number:orderNumber,user_id:user?.id||"",customer_name:clean(customer.name).slice(0,120),phone,email:clean(customer.email).slice(0,254),address:clean(customer.address).slice(0,500),city:clean(customer.city).slice(0,100),state:clean(customer.state).slice(0,100),pincode,payment_method:paymentMethod,razorpay_order_id:rpId||"",expected_total:provisionalTotal,items:raw.map(x=>({id:Number(x.id),qty:Number(x.qty),size:clean(x.size)}))};
 const {data:created,error}=await admin.rpc("sjc_create_order",{p_order:payload,p_idempotency_key:key});if(error){if(String(error.message||"").includes("INSUFFICIENT_STOCK"))return res.status(409).json({error:"Stock changed while checking out. Please refresh your bag."});if(String(error.message||"").includes("INVALID_SIZE"))return res.status(400).json({error:"One of the selected sizes is no longer available."});if(String(error.message||"").includes("PRODUCT_UNAVAILABLE"))return res.status(409).json({error:"A product in your bag is no longer available."});if(String(error.message||"").includes("INVALID_QUANTITY"))return res.status(400).json({error:"Please check item quantities."});if(String(error.message||"").includes("PRICE_CHANGED"))return res.status(409).json({error:"A product price changed during checkout. Refresh your bag and review the new total."});throw error}
 const actual=created?.razorpay_order_id||rpId;return res.status(201).json({orderNumber:created.order_number,existing:!!created.existing,razorpay:actual?{key:process.env.PUBLIC_RAZORPAY_KEY_ID||process.env.RAZORPAY_KEY_ID,orderId:actual,amount:Math.round(Number(created.total)*100)}:null,paymentStatus:created.payment_status,paymentMethod:paymentMethod});
 }catch(e){console.error("Order creation failed",e.message);return res.status(500).json({error:"Could not create order. Please retry; if you already submitted, do not submit again until the order is checked."})}}
