import {admin,getUser} from "../lib/supabase.js";
import Razorpay from "razorpay";
import crypto from "crypto";
export default async function(req,res){if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});try{
 const {razorpay_order_id,razorpay_payment_id,razorpay_signature,orderNumber}=req.body||{};
 if(![razorpay_order_id,razorpay_payment_id,razorpay_signature,orderNumber].every(x=>typeof x==="string"&&x.length>0&&x.length<200)||!/^[a-f0-9]{64}$/i.test(razorpay_signature))return res.status(400).json({error:"Invalid payment details"});
 if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return res.status(503).json({error:"Payment verification is not configured"});
 const expected=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET).update(razorpay_order_id+"|"+razorpay_payment_id).digest();const received=Buffer.from(razorpay_signature,"hex");if(received.length!==expected.length||!crypto.timingSafeEqual(expected,received))return res.status(400).json({error:"Invalid payment signature"});
 const {data:order,error:oe}=await admin.from("orders").select("order_number,user_id,razorpay_order_id,payment_status,total,order_status,payment_method").eq("order_number",orderNumber).eq("razorpay_order_id",razorpay_order_id).maybeSingle();if(oe)throw oe;if(!order)return res.status(404).json({error:"Order not found"});if(order.payment_status==="paid")return res.json({ok:true,alreadyProcessed:true});if(order.payment_method!=="ONLINE")return res.status(409).json({error:"This order is not an online payment"});
 // Do not let a logged-in user verify someone else's order; guest checkout remains supported through the unguessable order number + gateway signature.
 const user=await getUser(req,res);if(order.user_id&&order.user_id!==user?.id)return res.status(403).json({error:"This order belongs to another account"});
 const rp=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});const payment=await rp.payments.fetch(razorpay_payment_id);if(payment.order_id!==razorpay_order_id)return res.status(400).json({error:"Payment does not match this order"});if(Number(payment.amount)!==Math.round(Number(order.total)*100)||payment.currency!=="INR")return res.status(400).json({error:"Payment amount does not match the order"});if(payment.status!=="captured")return res.status(409).json({error:"Payment is not captured yet. Please wait or contact support."});
 const {data:updated,error}=await admin.from("orders").update({payment_status:"paid",order_status:order.order_status==="new"?"confirmed":order.order_status,razorpay_payment_id}).eq("order_number",orderNumber).eq("razorpay_order_id",razorpay_order_id).eq("payment_status","pending").select("order_number").maybeSingle();if(error)throw error;if(!updated){const {data:again}=await admin.from("orders").select("payment_status,razorpay_payment_id").eq("order_number",orderNumber).maybeSingle();if(again?.payment_status==="paid"&&again.razorpay_payment_id===razorpay_payment_id)return res.json({ok:true,alreadyProcessed:true});return res.status(409).json({error:"Order payment state changed. Please contact support."})}return res.json({ok:true});
 }catch(e){console.error("Payment verification failed",e.message);return res.status(500).json({error:"Payment verification failed. If money was deducted, contact support before retrying."})}}
