-- SHRI JI COLLECTION — additive customer reviews migration
-- Review submissions are private (pending) until an administrator approves them.
-- Safe to re-run. Does not delete or modify existing products, orders, or customers.

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  customer_name text not null check (char_length(btrim(customer_name)) between 2 and 80),
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(btrim(comment)) between 5 and 1000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists product_reviews_product_status_created_idx
  on public.product_reviews(product_id, status, created_at desc);
create index if not exists product_reviews_status_created_idx
  on public.product_reviews(status, created_at desc);

alter table public.product_reviews enable row level security;
drop policy if exists "public can read approved product reviews" on public.product_reviews;
create policy "public can read approved product reviews" on public.product_reviews
  for select to anon, authenticated using (status = 'approved');

-- Public visitors can read only approved reviews. All writes must go through server-side
-- APIs which verify admin access or create a pending review with an explicit status.
revoke all on public.product_reviews from anon, authenticated;
grant select on public.product_reviews to anon, authenticated;
grant all privileges on public.product_reviews to service_role;
grant usage, select on sequence public.product_reviews_id_seq to service_role;

create or replace function public.get_product_review_summary(p_product_ids bigint[])
returns table(product_id bigint, review_count bigint, average_rating numeric)
language sql stable security invoker set search_path = public
as $$
  select r.product_id, count(*)::bigint, round(avg(r.rating)::numeric, 1)
  from public.product_reviews r
  where r.status = 'approved'
    and r.product_id = any(coalesce(p_product_ids, '{}'::bigint[]))
  group by r.product_id;
$$;
revoke all on function public.get_product_review_summary(bigint[]) from public, anon, authenticated;
grant execute on function public.get_product_review_summary(bigint[]) to anon, authenticated, service_role;
