-- =====================================================================
-- SHRI JI COLLECTION — Supabase schema (v2). Safe to re-run.
-- Run the whole file once in: Supabase Dashboard → SQL Editor → New query.
-- Works on a fresh project AND upgrades the original v1 schema.
-- =====================================================================

-- ---------- Tables ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  category text not null,
  price numeric(12,2) not null,
  description text,
  material text,
  sizes text[] not null default '{}',
  image_urls text[] not null default '{}',
  stock integer not null default 0,
  active boolean not null default true
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  order_number text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  phone text not null,
  email text,
  address text not null,
  city text,
  state text,
  pincode text,
  payment_method text not null,
  payment_status text not null default 'pending',
  order_status text not null default 'pending',
  items jsonb not null,
  subtotal numeric(12,2) not null default 0,
  shipping numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  razorpay_order_id text,
  razorpay_payment_id text
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- ---------- v2 columns (upgrade path) ----------
alter table public.products add column if not exists slug text;
alter table public.products add column if not exists sale_price numeric(12,2);
alter table public.products add column if not exists updated_at timestamptz not null default now();

do $$
begin
  -- Orders created by v1 never reserved stock, so never give their stock back.
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='orders' and column_name='stock_restored') then
    alter table public.orders add column stock_restored boolean not null default false;
    update public.orders set stock_restored = true;
  end if;
end $$;

alter table public.orders add column if not exists idempotency_key text;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists admin_note text;
alter table public.orders add column if not exists updated_at timestamptz not null default now();
alter table public.orders alter column order_status set default 'pending';

update public.orders set order_status = 'pending' where order_status in ('new','');
update public.orders set order_status = lower(order_status);

-- Webhook de-duplication
create table if not exists public.payment_events (
  event_id text primary key,
  event text,
  created_at timestamptz not null default now()
);

-- ---------- Constraints (NOT VALID = enforced for new writes, old rows untouched) ----------
do $$
begin
  if not exists (select 1 from pg_constraint where conname='products_price_positive') then
    alter table public.products add constraint products_price_positive check (price > 0) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='products_stock_nonneg') then
    alter table public.products add constraint products_stock_nonneg check (stock >= 0) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='products_sale_below_price') then
    alter table public.products add constraint products_sale_below_price
      check (sale_price is null or (sale_price > 0 and sale_price < price)) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='orders_order_status_chk') then
    alter table public.orders add constraint orders_order_status_chk
      check (order_status in ('pending','confirmed','packed','shipped','delivered','cancelled')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='orders_payment_status_chk') then
    alter table public.orders add constraint orders_payment_status_chk
      check (payment_status in ('pending','paid','failed','cancelled')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='orders_payment_method_chk') then
    alter table public.orders add constraint orders_payment_method_chk
      check (payment_method in ('COD','ONLINE')) not valid;
  end if;
end $$;

-- ---------- Slugs + updated_at ----------
create or replace function public.set_product_defaults() returns trigger
language plpgsql as $$
begin
  if new.slug is null or new.slug = '' then
    new.slug := coalesce(nullif(trim(both '-' from left(regexp_replace(lower(new.name), '[^a-z0-9]+', '-', 'g'), 60)), ''), 'item')
                || '-' || new.id;
  end if;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists products_defaults on public.products;
create trigger products_defaults before insert or update on public.products
for each row execute function public.set_product_defaults();

update public.products set name = name where slug is null;   -- back-fill slugs

create unique index if not exists products_slug_key on public.products(slug);
create index if not exists products_active_cat_idx on public.products(active, category);
create index if not exists products_created_idx on public.products(created_at desc);
create index if not exists orders_user_idx on public.orders(user_id, created_at desc);
create index if not exists orders_created_idx on public.orders(created_at desc);
create unique index if not exists orders_rzp_order_key on public.orders(razorpay_order_id) where razorpay_order_id is not null;
create unique index if not exists orders_idem_key on public.orders(user_id, idempotency_key) where idempotency_key is not null;

-- ---------- Profile auto-creation ----------
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, full_name)
  values (new.id, new.raw_user_meta_data->>'full_name')
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

-- ---------- Row Level Security ----------
alter table public.profiles       enable row level security;
alter table public.products       enable row level security;
alter table public.orders         enable row level security;
alter table public.admin_users    enable row level security;
alter table public.payment_events enable row level security;

drop policy if exists "public can view active products" on public.products;
create policy "public can view active products" on public.products
  for select to anon, authenticated using (active = true);

drop policy if exists "users can view own profile" on public.profiles;
create policy "users can view own profile" on public.profiles
  for select to authenticated using (id = auth.uid());

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "users can view own orders" on public.orders;
create policy "users can view own orders" on public.orders
  for select to authenticated using (user_id = auth.uid());

-- No insert/update/delete policies exist for products, orders, admin_users or
-- payment_events: ONLY the server (service-role key) can change them.
revoke all on public.admin_users, public.payment_events from anon, authenticated;
revoke all on public.orders from anon;
revoke insert, update, delete, truncate on public.products from anon, authenticated;
revoke insert, update, delete, truncate on public.orders from authenticated;
revoke insert, delete, truncate on public.profiles from anon, authenticated;
revoke all on public.profiles from anon;
grant select on public.products to anon, authenticated;

-- Customers (if they ever query PostgREST directly) may not see internal columns.
revoke select on public.orders from authenticated;
grant select (id, created_at, order_number, user_id, customer_name, phone, email, address, city, state,
              pincode, payment_method, payment_status, order_status, items, subtotal, shipping, total)
  on public.orders to authenticated;

-- ---------- Atomic order functions (service-role only) ----------

-- Validates products, prices and stock, reserves stock and inserts the order in ONE transaction.
create or replace function public.create_order(
  p_user uuid, p_customer jsonb, p_items jsonb, p_method text, p_key text,
  p_shipping_flat numeric default 0, p_free_above numeric default null
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_existing public.orders;
  v_need record;
  v_item jsonb;
  v_prod public.products;
  v_qty int; v_size text; v_unit numeric;
  v_lines jsonb := '[]'::jsonb;
  v_sub numeric := 0; v_ship numeric := 0;
  v_order public.orders; v_number text;
begin
  if p_user is null then raise exception 'LOGIN_REQUIRED'; end if;
  if p_method not in ('COD','ONLINE') then raise exception 'INVALID_METHOD'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 20 then
    raise exception 'INVALID_ITEMS';
  end if;

  if p_key is not null then
    select * into v_existing from public.orders where user_id = p_user and idempotency_key = p_key;
    if found then return jsonb_build_object('existing', true, 'order', to_jsonb(v_existing)); end if;
  end if;

  -- Lock each product row (ordered by id: no deadlocks) and check stock for the combined quantity.
  for v_need in
    select (e->>'productId')::bigint as pid, sum((e->>'qty')::int) as qty
    from jsonb_array_elements(p_items) as t(e) group by 1 order by 1
  loop
    select * into v_prod from public.products where id = v_need.pid for update;
    if not found or not v_prod.active then raise exception 'UNAVAILABLE'; end if;
    if v_prod.stock < v_need.qty then raise exception 'OUT_OF_STOCK:%', v_prod.name; end if;
  end loop;

  for v_item in select value from jsonb_array_elements(p_items) loop
    select * into v_prod from public.products where id = (v_item->>'productId')::bigint;
    v_qty  := (v_item->>'qty')::int;
    v_size := nullif(trim(coalesce(v_item->>'size','')), '');
    if v_qty is null or v_qty < 1 or v_qty > 10 then raise exception 'INVALID_ITEMS'; end if;

    if coalesce(array_length(v_prod.sizes, 1), 0) > 0 then
      if v_size is null or not (v_size = any (v_prod.sizes)) then
        raise exception 'SIZE_REQUIRED:%', v_prod.name;
      end if;
    else
      v_size := null;
    end if;

    v_unit := case when v_prod.sale_price is not null and v_prod.sale_price > 0 and v_prod.sale_price < v_prod.price
                   then v_prod.sale_price else v_prod.price end;
    v_sub := v_sub + v_unit * v_qty;
    v_lines := v_lines || jsonb_build_object(
      'product_id', v_prod.id, 'name', v_prod.name, 'slug', v_prod.slug, 'size', v_size,
      'qty', v_qty, 'unit_price', v_unit, 'image', v_prod.image_urls[1]);
    update public.products set stock = stock - v_qty where id = v_prod.id;
  end loop;

  v_ship := case when p_free_above is not null and v_sub >= p_free_above then 0
                 else coalesce(p_shipping_flat, 0) end;
  v_number := 'SJC-' || to_char(now() at time zone 'Asia/Kolkata', 'YYMMDD') || '-'
              || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 5));

  insert into public.orders(order_number, user_id, customer_name, phone, email, address, city, state, pincode,
                            payment_method, payment_status, order_status, items, subtotal, shipping, total,
                            idempotency_key)
  values (v_number, p_user, p_customer->>'name', p_customer->>'phone', nullif(p_customer->>'email',''),
          p_customer->>'address', p_customer->>'city', p_customer->>'state', p_customer->>'pincode',
          p_method, 'pending', 'pending', v_lines, v_sub, v_ship, v_sub + v_ship, p_key)
  returning * into v_order;

  return jsonb_build_object('existing', false, 'order', to_jsonb(v_order));
end $$;

-- Gives reserved stock back exactly once.
create or replace function public.restore_order_stock(p_order bigint) returns void
language plpgsql security definer set search_path = public as $$
declare v_o public.orders; v_i jsonb;
begin
  select * into v_o from public.orders where id = p_order for update;
  if not found or v_o.stock_restored then return; end if;
  for v_i in select value from jsonb_array_elements(v_o.items) loop
    update public.products set stock = stock + coalesce((v_i->>'qty')::int, 0)
    where id = (v_i->>'product_id')::bigint;
  end loop;
  update public.orders set stock_restored = true where id = p_order;
end $$;

-- Admin (p_user null) or customer (p_user set; may only cancel own unpaid pending order).
create or replace function public.set_order_status(p_order_number text, p_status text, p_user uuid default null)
returns public.orders
language plpgsql security definer set search_path = public as $$
declare v_o public.orders;
begin
  if p_status not in ('pending','confirmed','packed','shipped','delivered','cancelled') then
    raise exception 'INVALID_STATUS';
  end if;
  select * into v_o from public.orders where order_number = p_order_number for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if p_user is not null then
    if v_o.user_id is distinct from p_user then raise exception 'NOT_FOUND'; end if;
    if p_status <> 'cancelled' or v_o.order_status <> 'pending' or v_o.payment_status = 'paid' then
      raise exception 'NOT_ALLOWED';
    end if;
  end if;
  if v_o.order_status = 'cancelled' and p_status <> 'cancelled' then raise exception 'CANCELLED_LOCKED'; end if;
  if p_status in ('confirmed','packed','shipped','delivered')
     and v_o.payment_method = 'ONLINE' and v_o.payment_status <> 'paid' then
    raise exception 'PAYMENT_PENDING';
  end if;

  if p_status = 'cancelled' then
    perform public.restore_order_stock(v_o.id);
    update public.orders set order_status = 'cancelled', updated_at = now(),
      payment_status = case when payment_status in ('pending','failed') and payment_method = 'ONLINE'
                            then 'cancelled' else payment_status end
    where id = v_o.id returning * into v_o;
  else
    update public.orders set order_status = p_status, updated_at = now(),
      payment_status = case when p_status = 'delivered' and payment_method = 'COD' and payment_status = 'pending'
                            then 'paid' else payment_status end,
      paid_at = case when p_status = 'delivered' and payment_method = 'COD' and payment_status = 'pending'
                     then now() else paid_at end
    where id = v_o.id returning * into v_o;
  end if;
  return v_o;
end $$;

-- Idempotent: called by both /api/verify-payment and the Razorpay webhook.
create or replace function public.mark_order_paid(p_razorpay_order_id text, p_payment_id text, p_amount_paise bigint default null)
returns public.orders
language plpgsql security definer set search_path = public as $$
declare v_o public.orders;
begin
  select * into v_o from public.orders where razorpay_order_id = p_razorpay_order_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if p_amount_paise is not null and p_amount_paise <> round(v_o.total * 100) then
    raise exception 'AMOUNT_MISMATCH';
  end if;
  if v_o.payment_status = 'paid' then return v_o; end if;
  update public.orders set
    payment_status = 'paid', razorpay_payment_id = p_payment_id, paid_at = now(), updated_at = now(),
    order_status = case when order_status = 'pending' then 'confirmed' else order_status end,
    admin_note = case when order_status = 'cancelled'
      then trim(coalesce(admin_note || ' | ', '') || 'PAID AFTER CANCELLATION - refund or reinstate manually')
      else admin_note end
  where id = v_o.id returning * into v_o;
  return v_o;
end $$;

create or replace function public.mark_payment_failed(p_razorpay_order_id text) returns void
language sql security definer set search_path = public as $$
  update public.orders set payment_status = 'failed', updated_at = now()
  where razorpay_order_id = p_razorpay_order_id and payment_status = 'pending';
$$;

-- Daily clean-up: cancels unpaid online orders and releases their stock.
create or replace function public.expire_unpaid_orders(p_hours int default 24) returns int
language plpgsql security definer set search_path = public as $$
declare v record; n int := 0;
begin
  for v in select order_number from public.orders
           where payment_method = 'ONLINE' and payment_status in ('pending','failed')
             and order_status = 'pending' and created_at < now() - make_interval(hours => p_hours)
  loop
    perform public.set_order_status(v.order_number, 'cancelled');
    n := n + 1;
  end loop;
  return n;
end $$;

-- Only the server (service_role) may call these.
revoke all on function public.create_order(uuid, jsonb, jsonb, text, text, numeric, numeric) from public, anon, authenticated;
revoke all on function public.restore_order_stock(bigint) from public, anon, authenticated;
revoke all on function public.set_order_status(text, text, uuid) from public, anon, authenticated;
revoke all on function public.mark_order_paid(text, text, bigint) from public, anon, authenticated;
revoke all on function public.mark_payment_failed(text) from public, anon, authenticated;
revoke all on function public.expire_unpaid_orders(int) from public, anon, authenticated;
grant execute on function public.create_order(uuid, jsonb, jsonb, text, text, numeric, numeric) to service_role;
grant execute on function public.restore_order_stock(bigint) to service_role;
grant execute on function public.set_order_status(text, text, uuid) to service_role;
grant execute on function public.mark_order_paid(text, text, bigint) to service_role;
grant execute on function public.mark_payment_failed(text) to service_role;
grant execute on function public.expire_unpaid_orders(int) to service_role;

-- ---------- Site settings (logo + home picture, edited from /admin -> Site) ----------
create table if not exists public.site_settings (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);
alter table public.site_settings enable row level security;
drop policy if exists "public can read site settings" on public.site_settings;
create policy "public can read site settings" on public.site_settings for select to anon, authenticated using (true);
revoke insert, update, delete, truncate on public.site_settings from anon, authenticated;
grant select on public.site_settings to anon, authenticated;

-- ---------- Storage: public-read bucket, uploads only through the server ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 3145728, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit,
                               allowed_mime_types = excluded.allowed_mime_types;

-- Public bucket URLs work without a policy. The old SELECT policy also allowed LISTING every file; remove it.
drop policy if exists "public can view product images" on storage.objects;
-- No insert/update/delete policies: browsers cannot write to storage; the server (service role) does.

-- ---------- After creating your own account, make yourself admin ----------
--   insert into public.admin_users(user_id) values ('PASTE-YOUR-USER-UUID');
